#!/bin/bash
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/0
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/2
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/4
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/6
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/8
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/10
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/12
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/14
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/16
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/18
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/20
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/22
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/24
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/26
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/28
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/30
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/32
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/34
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/36
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/38
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/40
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/42
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/44
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/46
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/48
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/50
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/52
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/54
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/56
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/58
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/60
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/62
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/64
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/66
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/68
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/70
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/72
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/74
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/76
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/78
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/80
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/82
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/84
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/86
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/88
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/90
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/92
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/94
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/96
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/98
sleep 0.5
cat /home/administrator/Desktop/.base4/cpu/system/framework/aesthetic/progress/100
sleep 1
